backend/core/urls.py
from django.urls import path
from .views import index, personagens

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('personagens/', personagens, name='personagens'),
]

backend/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('backend.core.urls', namespace='core')), 
    path('admin/', admin.site.urls),
]

backend/core/models.py
from django.db import models

# Create your models here.

backend/core/forms.py
from django import forms

class PesquisaPersonagens(forms.Form):
    nome = forms.CharField(
        widget=forms.CharField(
            attrs={'placeholder' : "Digite o nome certo do personagem, ou parcial"}
        )
    )
    nome_preciso = forms.BooleanField(default=False)
    password = forms.CharField(
        label= "Senha",
        widget=forms.PasswordInput(
            attrs={'placeholder' : "Digite sua senha"}
        )
    )

backend/core/views.py
from django.shortcuts import render
from . import marvel

def index(request):
    return render(request, 'core/index.html')

def personagens(request):
    cabecalho_string = marvel.cabecalho()
    url_sufix = 'characters'
    marvel_json = marvel.get_marvel_json(url_sufix, cabecalho_string)
    print(marvel_json)
    if request.POST:
        if 'pesquisaunica': 
            print('pesquisaunica')
        elif 'pesquisalista':
            print('pesquisalista')
    return render(request, 'core/personagens.html')

backend/core/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">

    <!--Para carregar os arquivos estaticos na pagina.-->
    {% load static %}

    <head>
        <meta charset="UTF-8">
        <!--Para ter compatibilidade com internet explore antigo-->
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <!--Para moldar dentro de navegadores de mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- CSS -->
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'extra/style/style.css' %}"/>
        <!-- Titulo-->
        <title>
            {% block title %}{% endblock title %}
        </title>
        {% block css %}{% endblock css %}
    </head>

    <body>
        <header>
            {% include 'partials/_navbar.html' %}
        </header>
        <main>
            <!--A linha abaixo serve para indicar onde no base.html será incluido informações de outros html-->
            {% block content %}{% endblock content %}
        </main>
        <!-- Scripts -->
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        {% block js %}{% endblock js %}
    </html>

backend/core/templates/core/index.html
<!--Para avisar que a pagina é uma extenção da base.html-->
{% extends 'base.html' %}

<!--Para carregar os arquivos estaticos na pagina.-->
{% load static %}
<!--Bloco que define o titulo na pagina-->

{% block title %}Marvel Api Consume{% endblock %}
<!--Para indicar qual bloco será inserida no base.html-->

{% block content %}

    <div class="container">
        <div class="col-lg-9 offset-lg-1">
            <section>
                <br>
                <br>
                <h2 class="text-center">Site para expor informações dos quadrinhos da marvel.</h2>
            </section>
        </div>
    </div>

{% endblock %}

backend/core/templates/core/personagens.html
<!--Para avisar que a pagina é uma extenção da base.html-->
{% extends 'base.html' %}

<!--Para carregar os arquivos estaticos na pagina.-->
{% load static %}
<!--Bloco que define o titulo na pagina-->

{% block title %}Personagens Marvel{% endblock %}
<!--Para indicar qual bloco será inserida no base.html-->

{% block content %}

    <div class="container">
        <div class="col-lg-9 offset-lg-1">
            <section>
                <br>
                <br>
                <h2 class="text-center">Procure informações sobre os personagens.</h2>
            </section>
            <hr>
            <form method="post" class="row justify-content-center" action="." >
                {% csrf_token %}
                <h3 class="text-center" data-info="textoLogin">Pesquisa de personagem individualmente.</h3>
                <div class="row">
                    <div class="form-group col-lg-9">
                        <label for="pequeisaPersonagemInput">Nome do personagem</label>
                        <input type="text" class="form-control" id="pequeisaPersonagemInput" aria-describedby="pequeisaPersonagemHelp" placeholder="Digite o nome do personagem">
                        <small id="pequeisaPersonagemHelp" class="form-text text-muted">Por favor digite o nome do personagem em ingles.</small>
                    </div>
                    <div class="col-sm-2 botaoVerde" style="margin-top: 15px;" >
                        <button name="pesquisaunica" class="w-100 btn btn-outline-primary" type="submit">Pesquisar</button>
                    </div>
                </div>
            </form>
            <hr>
            <form method="post" class="row justify-content-center" action="." >
                {% csrf_token %}
                <h3 class="text-center" data-info="textoLogin">Lista de personagens.</h3>
                <div class="w-100"></div>
                <div class="col-sm-2 botaoVerde">
                    <button name="pesquisalista" class="w-100 btn btn-outline-primary" type="submit">Pesquisar</button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

backend/core/templates/partials/_navbar.html
<!--Para carregar os arquivos estaticos na pagina.-->
{% load static %}

<section data-info="navbar-login-cadastro">
    <div class="container">
        <div class="col-lg-9 offset-lg-1">
            <nav class="navbar navbar-expand-sm bg-light navbar-light">
                <ul class="navbar-nav">
                    <div class="nav-item" style="margin-left: 10px;" data-info="botaoCadastro">
                        <a class="btn btn-outline-success" role="button" href="{% url 'core:index' %}">Home Page</a>
                    </div>
                    <div class="nav-item" style="margin-left: 10px;" data-info="botaoCadastro">
                        <a class="btn btn-outline-success" role="button" href="{% url 'core:personagens' %}">Personagens</a>
                    </div>              
                </ul>
            </nav>
        </div>
    </div>
</section>

backend/core/templates/partials/_paginador.html
<!--Para carregar os arquivos estaticos na pagina.-->
{% load static %}

<section class="top-catagory-area section-padding-20-0">
    <div class="container ">

        {% if paginacao.has_other_pages %}
            <ul class="pagination justify-content-end">

                {% if paginacao.has_previous %}
                    <li class="page-item">
                        <a href="?page= {{ paginacao.previous_page_number }}" class="page-link">&laquo;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">&laquo;</a>
                    </li>
                {% endif %}

                {% for pagina in paginacao.paginator.page_range %}
                    {% if paginacao.number == pagina %}
                        <li class="page-item active">
                            <a class="page-link">{{ pagina }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a href="?page={{ pagina }}" class="page-link">{{ pagina }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                {% if paginacao.has_next %}
                    <li class="page-item">
                        <a href="?page={{ paginacao.next_page_number }}" class="page-link">&raquo;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">&raquo;</a>
                    </li>
                {% endif %}

            </ul>
        {% endif %}
    </div>
</section>

backend/core/templates/partials/_sidebar.html
<!--Para carregar os arquivos estaticos na pagina.-->
{% load static %}

<nav data-info="navSideBar">
    <div id="sideBar" class="sidenav aberto">

        <div class="container-fluid">

            <a class="collapse-escolha" data-bs-toggle="collapse" href="#collapseVagas" aria-expanded="false"
                aria-controls="collapseVagas">
                Vagas
            </a>

            <div class="collapse" id="collapseVagas">
                <a class="collapse-opcoes" href="{% url 'todasvagas' %}">Todas Vagas</a>

                {% if request.user.tipo_user == "CAND" %}
                    <a class="collapse-opcoes" href="#">Vagas Candidatadas</a>

                {% elif request.user.tipo_user == "EMPR" %}
                    <a class="collapse-opcoes" href="{% url 'criandovaga' %}">Nova Vagas</a>
                    <a class="collapse-opcoes" href="{% url 'visualizandosuasvagas' %}">Suas Vagas</a>
                {% endif %}
                <hr>
            </div>

            {% if request.user.tipo_user == "CAND" %}
                <a class="collapse-escolha" data-bs-toggle="collapse" href="#collapseSeuPerfil" aria-expanded="false"
                    aria-controls="collapseSeuPerfil">
                    Seu Perfil
                </a>
                <div class="collapse" id="collapseSeuPerfil">
                    <a class="collapse-opcoes" href="{% url 'visualizandoperfil' %}">Vizualizar Perfil</a>
                    <!--#TODO <a class="collapse-opcoes" href="#">Editar Perfil</a> -->
                    <hr>
                </div>

            {% elif request.user.tipo_user == "EMPR" %}
                <a class="collapse-escolha" data-bs-toggle="collapse" href="#collapseSuaInfo" aria-expanded="false"
                    aria-controls="collapseSuaInfo">
                    Informações da empresa
                </a>
                <div class="collapse" id="collapseSuaInfo">
                    <a class="collapse-opcoes" href="{% url 'visualizandoinfo' %}">Vizualizar Informações</a>
                    <!--#TODO <a class="collapse-opcoes" href="#">Editar Informações</a> -->
                    <hr>
                </div>



            {% endif %}

            <hr>
            <a class="collapse-escolha" href="{% url 'logout' %}">Logout</a>

        </div>

    </div>

    <button onclick="manipularNav()" class="btn shadow-none" id="botaoSideBar">
        <svg width="16" height="16">
            <use href="{% static 'bootstrap/icons/list.svg' %}#listsvg"></use>
        </svg>
    </button>
</nav>